# Generated by Django 5.1.7 on 2025-04-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_leaverequest_status_profile_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='document',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
