# Generated by Django 5.1.7 on 2025-04-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_leaverequest1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest1',
            old_name='employee_name',
            new_name='Employee_name',
        ),
        migrations.RenameField(
            model_name='leaverequest1',
            old_name='end_date',
            new_name='End_date',
        ),
        migrations.RenameField(
            model_name='leaverequest1',
            old_name='leave_type',
            new_name='Leave_type',
        ),
        migrations.RenameField(
            model_name='leaverequest1',
            old_name='start_date',
            new_name='Start_date',
        ),
        migrations.RemoveField(
            model_name='leaverequest1',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='leaverequest1',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
