# Generated by Django 5.1.7 on 2025-04-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_rename_employee_name_leaverequest1_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest1',
            name='Status',
        ),
        migrations.AddField(
            model_name='leaverequest1',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
