# Generated by Django 5.1.7 on 2025-04-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
    ]
