# Generated by Django 5.1.7 on 2025-04-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_remove_feedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest1',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
