# Generated by Django 5.1.7 on 2025-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_remove_attendance_user_delete_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
    ]
